stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - python -m unittest discover

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
